CC=gcc
LFLAGS=-lm

all:
	$(CC) -o fp1 fp1.c $(LFLAGS)
	$(CC) -o fp2 fp2.c $(LFLAGS)
	$(CC) -o fp3 fp3.c $(LFLAGS)
	$(CC) -o fp4 fp4.c $(LFLAGS)
	$(CC) -o fp5 fp5.c $(LFLAGS)
	$(CC) -o fp6 fp6.c $(LFLAGS)
